// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"DK_Mouse_System","status":true,"description":"v.1.2.0 [MV|MZ] Allows you to change the mouse cursor, activate events by clicking, hovering, etc.","parameters":{"defaultCursor":"","iconSynonyms":"[]","transferIcon":"0","destination":"{\"type\":\"default\",\"offsetX\":\"0\",\"offsetY\":\"0\",\"color\":\"white\",\"outlineColor\":\"default\",\"blendMode\":\"1\",\"scale\":\"1.00\",\"animation\":\"{\\\"bounceRate\\\":\\\"20\\\",\\\"minOpacity\\\":\\\"16\\\",\\\"maxOpacity\\\":\\\"192\\\",\\\"minScale\\\":\\\"0.15\\\",\\\"maxScale\\\":\\\"1.50\\\"}\"}"}},
{"name":"ReplicateCommands","status":true,"description":"","parameters":{}}
];
